#namespace:
#  name: quorum-test
sep_deployment_files: true
nodes:
  number: 3
service:
  type: NodePort
quorum:
  consensus: raft
  Node_DataDir: /etc/quorum/qdata
  Key_Dir_Base: out/config
  Permissioned_Nodes_File: out/config/permissioned-nodes.json
  Genesis_File: out/config/genesis.json
  quorum:
    Raft_Port: 50400
    Quorum_Version: 2.5.0
  storage:
    Type: PVC
    Capacity: 200Mi
  tm:
    Name: tessera
    Tm_Version: 0.10.2
    Port: 9000
    3Party_Port: 9080
    Tessera_Config_Dir: out/config
geth:
  Node_RPCPort: 8545
  NodeP2P_ListenAddr: 21000
  network:
    id: 10
    public: false
  verbosity: 9
  Geth_Startup_Params: --rpccorsdomain=\"*\"